### ISSUE TITLE
[E4] Duda sobre  Bewitching Tome

### ISSUE THREAD

**Issue by cristobalSaravia** [franciscogazitua/IIC2113-2024#108]
No me quedó claro a que se refiere la descripción con "X % del ataque del rival". Se refiere al stat Atk o al daño que hace el rival al atacar, y si es así, se refiere al primer ataque del rival?

**Comment by franciscogazitua** [comment]
Hola

Se refiere a Atk. Concuerdo en que es poco consistente con el resto de habilidades.
Como referencia, los stats significan lo siguiente:

- Atk = ataque
- Spd = velocidad
- Def = defensa
- Res = resistencia

Saludos

**Comment by cristobalSaravia** [comment]
Vale, muchas gracias.
