### ISSUE TITLE
[E4] Duda sobre daño después del combate

### ISSUE THREAD

**Issue by gianpisani** [franciscogazitua/IIC2113-2024#110]
![data/E4-1-Tests/001__Hybrid_Atk_Def_Push.txt](https://github.com/franciscogazitua/IIC2113-2024/assets/105687064/258f5a46-098a-45b0-acef-a01001b8d4b8)

**Test:** data/E4-1-Tests/001__Hybrid_Atk_Def_Push.txt

Hola, 

Tengo una duda con el daño que se hace después del combate. En este caso, en la ronda 4, ``Eirika`` terminó con ``13 de vida``. En la ronda 5, ``Lyn`` ataca a ``Eirika`` con ``12 de daño`` y al final de combate ``Eirika`` recibe ``5 de daño``. Con esto la vida de ``Eirika`` debería quedar en 0 (13-17). Lo que veo que está pasando es que se está anunciado que recibe 5 de daño al final del combate pero no se le aplica a la unidad realmente, únicamente se aplica el primer daño hecho por ``Lyn``. (Y me imagino que es porque termina la partida, pero no tiene sentido en ese caso anunciar el efecto de daño después del combate).

Quedo atento a su respuesta, muchas gracias.

**Comment by franciscogazitua** [comment]
Hola

Como se menciona en el enunciado, las habilidades de daño después del combate no pueden matar a la unidad, dejando su HP en al menos 1. Adicionalmente, estas habilidades suceden independiente de que suceda en el combate, por lo que la única manera en la que Eirika no hubiese recibido esos 5 de daño es que haya muerto durante el combate

Saludos

**Comment by gianpisani** [comment]
Gracias
