### ISSUE TITLE
[E4] duda Test E4-random 009

### ISSUE THREAD

**Issue by cristobalSaravia** [franciscogazitua/IIC2113-2024#116]
Hola, tengo un problema con el test 9 de los E4-2 random
![image](https://github.com/franciscogazitua/IIC2113-2024/assets/110921243/6ebed188-5171-4c23-b6f8-ab88dbc94cde)
Haciendo el calculo de Mastermind obtengo que:
Bonus unidad: X = (9+9)*0,8 = 14,4
Penalty rival: Y = (3+3)*0,8 = 4,8

X + Y = 19,2

Entonces, al truncar los decimales, debería resultar que Roy hace +19 de daño en cada ataque, pero en el test aparece +18.
Esto está bien?

**Comment by RodrigoToroIcarte** [comment]
Buen punto. Debimos haber aclarado esto en el enunciado. El X y el Y se truncan de manera independiente. Por eso queda X = 14, Y = 4, X+Y = 18.

Ya actualicé esto en el enunciado para las próximas generaciones. Gracias por el comentario :)

**Comment by cristobalSaravia** [comment]
Vale, muchas gracias.
