### ISSUE TITLE
[E1] No se puede comprimir la entrega

### ISSUE THREAD

**Issue by rutercrack** [franciscogazitua/IIC2113-2024#12]
Después de haber pegado "data" y los json de characters y skills en la entrega, windows no me deja comprimir el archivo diciendo que hay caracteres que no permiten la compresión. ¿Debería borrar data de la carpeta antes de comprimirla?

Gracias de antemano!

**Comment by franciscogazitua** [comment]
Hola, la Issue me aparece cerrada. Lo lograste solucionar?? Imagino que viste la Issue #7, pero pregunto para confirmar

**Comment by rutercrack** [comment]
> Hola, la Issue me aparece cerrada. Lo lograste solucionar?? Imagino que viste la Issue #7, pero pregunto para confirmar

Hola, no la pude solucionar, efectivamente lo cerré para no saturar las issues dado que ya había una sobre lo mismo. El tema es que intenté ver si tenía que ver con la herramienta que descomprime el zip pero tal parece que el nativo de windows, rar y 7zip dan el mismo problema. ¿En serio la única solución es cambiar los archivos manualmente?

**Comment by franciscogazitua** [comment]
Hola, estamos investigando aún el problema. La principal dificultad que hemos tenido es que al utilizar distintas formas de compilar y descompilar, como por ejemplo el nativo de windows, nativo de linux o 7zip no he logrado replicar el problema. Mientras trabajamos en una solución recomendaría cambiar a mano el caracter de los archivos (deberían ser 12) para que puedas subir tu entrega. Esperamos tener más novedades cuando encontremos una solución.

**Comment by franciscogazitua** [comment]
Como aclaración, esos tests se evalúan en la E4, así que no deberían afectar en nada tu nota de esta entrega.

**Comment by rutercrack** [comment]
> Como aclaración, esos tests se evalúan en la E4, así que no deberían afectar en nada tu nota de esta entrega.

Acabo de descubrir algo: si bien al descomprimir pro alguna razón se cambia el char especifico, si lo comprimo con 7zip o rar me deja sin problemas, es el de windows el que no te deja comprimir (eso si, no tengo idea de como queda el char especifico después de la compresión, quizás se revierte al char original o quizás queda del formato al que lo transformó Windows)
