### ISSUE TITLE
[E4] Habilidades interfaz gráfica

### ISSUE THREAD

**Issue by cristobalSaravia** [franciscogazitua/IIC2113-2024#130]
Hola, quería preguntar si es intencional que en la interfaz gráfica se puedan elegir habilidades que no se implementaron en las entregas (por ej: alacrity). Si es así, debemos mostrar la misma ventana de equipo invalido?

**Comment by RodrigoToroIcarte** [comment]
No hagas nada al respecto. Puedes asumir que al testear tu entrega solo usaremos skills que les hayamos pedido implementar en el proyecto :)

De hecho, lo más probable es que solo usamos skills de la E2 cosa que igual puedan tener los puntos por la interfaz gráfica a pesar de no pasar todos los test cases.

**Comment by cristobalSaravia** [comment]
Ok, muchas gracias
