### ISSUE TITLE
[E1] Duda E1-InvalidTeams

### ISSUE THREAD

**Issue by pascual1** [franciscogazitua/IIC2113-2024#153]
No logro encontrar el error de formato en varios de los test cases de equipos inválidos. En 000.txt por ejemplo se entregan personajes y skills válidas. Tenemos que asumir que la presencia de skills en esta entrega hace inválido al archivo?

**Comment by franciscogazitua** [comment]
Hola

El especifico de que hace o no un equipo inválido se encuentra explicado en los enunciados del proyecto, pero para verificar si un equipo es válido o no debes ver si rompe alguna de las reglas establecidas para formar equipos. 

Por ejemplo, en el test `000.txt` Eliwood del segundo equipo tiene tres habilidades, cuando puede tener un máximo de dos

Saludos

**Comment by pascual1** [comment]
Muchas gracias!
