### ISSUE TITLE
Duda sobre la validación de equipos

### ISSUE THREAD

**Issue by martina-abello** [franciscogazitua/IIC2113-2024#160]
Hasta ahora pensaba que tenía más sentido validar primero el archivo de equipos elegido, y luego construir los equipos si eran válidos, tipo para no construir equipos inválidos, y me funciona perfecto al menos para la entrega 1, pero me entró la duda de si acaso no es mejor validar después por si en algún momento cambia el cómo se construyen los equipos (ejemplo si nos los dan en otro tipo de archivo, o los players tienen que elegir cada character que quieren uno a uno, o algo).

Básicamente mi pregunta es si esto último va a pasar, en cuyo caso es obvio mejor validar los equipos ya construidos, o si está bien validar antes (porque si los equipos son inválidos el mensaje debe anunciar que el *archivo* de equipos no es válido), o si en cualquier caso es mejor validar después de construir los equipos por temas de dependencia, aunque no vaya a afectar en el código final.

Gracias de antemano!

**Comment by RodrigoToroIcarte** [comment]
Hola,

Disculpa que me haya demorado en contestar. En general contesto más rápido :/

Puedes validar antes o después. Da un poco lo mismo. Las reglas para validar un equipo no cambiarán a lo largo del proyecto. De hecho, los únicos ejemplos de equipos inválidos son los de la E1. En el resto de las entregas siempre les daremos equipos válidos (porque lo que queremos evaluar son las nuevas habilidades).
