### ISSUE TITLE
¿Qué afecta Beorc's Blessing?

### ISSUE THREAD

**Issue by martina-abello** [franciscogazitua/IIC2113-2024#165]
Según su descripción neutraliza los bonus del rival, pero no sé si se refiere a las habilidades en la _categoría_ Bonus, o a todas las habilidades que entreguen un bonus al rival, incluyendo HP +15 que está en Alteración de Stats Base, y/o las habilidades Híbridas (en cuyo caso, ¿neutralizaría también los penaltis causados por esas habilidades?).

Gracias de antemano.

**Comment by franciscogazitua** [comment]
Hola

Creo que la confusión viene en que habilidades como `Beorc's Blessing` no neutralizan habilidades, sino que efectos. Si una habilidad tiene un efecto de bonus, este será neutrilizado por efectos de neutralización de Bonus. Bonus es una categoría de efecto especifica, por lo que sus neutralizadores no afectarán ningun otro efecto, sea Penalty, Alteración de Stats Base u otro. Una habilidad hibrida puede tener más de un tipo de efecto, por lo que `Beorc's Blessing` solo neutralizará aquellos efectos que sean Bonus.

Saludos

**Comment by martina-abello** [comment]
Sorry, no me quedó claro.

**Comment by martina-abello** [comment]
Si una unidad tiene HP +15, Beorc's Blessing lo neutraliza? Si lo hace, como es sólo durante el combate, la unidad vuelve a tener 15 puntos extra de HP contra otras unidades? y solo recupera su HP máximo, o el actual? 
Si una unidad tiene Lance Power, Beorc's Blessing neutraliza sólo el Atk+10, o también el Def-10?

**Comment by franciscogazitua** [comment]
Hola

Como decía, `Beorc's Blessing` neutraliza efectos de bonus, no habilidades completas. `HP +15` no tiene efectos de Bonus, por lo que no habra neutralización. `Lance Power` tiene un efecto de Bonus y un efecto de Penalty, por lo que `Beorc's Blessing` solo neutralizará el Bonus y el Penalty no se ve afectado.

Saludos

**Comment by RodrigoToroIcarte** [comment]
¡Hola @martina-abello !

Es más fácil de lo que crees :)

El HP+15 no se considera un bonus. Es un efecto constante que se aplica al inicio del juego y queda ahí por siempre. No existirá nada que lo quite o neutralice pues, de lo contrario, se dan todos los casos bordes que mencionas.

Desde un punto de vista super pragmático, uno podría partir el juego, ver quién tiene efecto de +15HP y aumentarle la vida de inmediato. Luego de eso no tienes que volver a preocuparte por esa habilidad.

Los "bonus" como tal son los efectos que suman algún valor a las stats durante un combate. Esos bonus afectan el Atk, Def, Res o Spd de la unidad. Ninguno de ellos afecta el Hp. 

Por lo mismo, una forma fácil de pensar `Beorc's Blessing` es que neutraliza todo bonus que aumenten el Atk, Def, Res o Spd del rival.

Si te quedan dudas nos preguntas :)

**Comment by martina-abello** [comment]
Muchas graciasss ^^
