### ISSUE TITLE
[E3] Duda con test 019 (Moon-Twin Wing)

### ISSUE THREAD

**Issue by martina-abello** [franciscogazitua/IIC2113-2024#192]
De acuerdo con el test, en la ronda 8 no se activa la reducción de daño de Moon-Twin Wing para Alm, pese a que la condición de tener mayor Spd se cumple. A qué se debe?

**Comment by franciscogazitua** [comment]
En esa ronda, el HP inicial de Alm es de 8, por lo que no se cumple la condición de que `HP >= 25%`. Se deben cumplir ambas condiciones para que Moon-Twin Wing se active, por lo que aunque se cumple la condición de Spd no se activa la habilidad.

Saludos
