### ISSUE TITLE
Duda con Divine Recreation

### ISSUE THREAD

**Issue by martina-abello** [franciscogazitua/IIC2113-2024#193]
Cuando se habla de reducción de daño por otras habilidades, eso incluye penalties en el Atk? De hecho, afectan en algo los bonus y las nulificaciones de bonus/penalty??

tipo, el daño original es atk base del rival * wtb - def base de la unidad, o atk base + bonus * wtb - (def base + bonus), o cómo? En verdad estoy cachando 0 de cómo funciona esta habilidad. 

gracias de antemano.

**Comment by franciscogazitua** [comment]
Hola

Si bien las habilidades de bonus y penalty pueden provocar que una unidad reciba menos daño, estos no reducen el daño en si, por lo que con "otras habilidades" nos referimos a cualquier habilidad que tenga un efecto de reducción de daño porcentual o reducción de daño absoluto.

Espero que eso haya respondido tu pregunta. Saludos

**Comment by martina-abello** [comment]
Sii muchas gracias ^^
