### ISSUE TITLE
[E3] Duda Guard Bearing

### ISSUE THREAD

**Issue by martina-abello** [franciscogazitua/IIC2113-2024#194]
No entiendo cómo funciona esta habilidad, o cuándo se aplica. Si la unidad que lo tiene inicia el combate con otra el valor es 60, OK, pero qué pasa si luego inicia combate contra otra unidad distinta? Es 60 o 30? Porque sería la primera vez que incia combate contra esa unidad, no?

gracias de antemano

**Comment by franciscogazitua** [comment]
Hola

La habilidad se refiere a la primera vez en todo el juego en que la unidad inicia el combate, independiente contra quien, y la primera vez en todo el juego en que la unidad es quien se defiende, independiente contra quien.

Saludos

**Comment by martina-abello** [comment]
Grazie
