### ISSUE TITLE
[E3] Acerca de Boundaries

### ISSUE THREAD

**Issue by martina-abello** [franciscogazitua/IIC2113-2024#200]
hay que encapsular absolutamente todos los atributos que sean Array, List, etc? o hay algún caso en que no sea necesario/pueda bajar puntaje?

lo otro, si tengo un foreach sobre el atributo antes de haberlo encapsulado, para mantenerlo es mejor que la clase tenga un método que devuelva una lista o un array, y que el foreach se ejecute sobre eso, o tener un método que saque uno a uno los elementos, y hacer el foreach sobre el largo del objeto (con un método Count o un atributo Length, por ejemplo)?

gracias de antemano

**Comment by cahinostroza** [comment]
Hola @martina-abello.

Hay que encapsular todo uso de alguna clase del namespace Collections (List, Dictionaty, Set, etc), Array no pertenece a este namespace, por lo tanto, no es necesario encapsular su uso.

Es decir, si es que tienes una EDD para Unit de este estilo: 
```
public class Unit {
  public string Name;
  /* ... */
  public List<string> AbilityNames;
  /* ... */
}
```
Podrías reemplazarla por:
```
public class Unit {
  public string Name;
  /* ... */
  public string[] AbilityNames;
  /* ... */
}
```

También puede que si utlizabas una clase del namespace Collections en un atributo de una clase que representaba un objeto, ya esté encapuslada. Como el ejemplo que vimos en clases de `ConditionCatalog`:
```
public class ConditionCatalog {
  private Dictionary<string,Condition> _conditions = new();

  public Condition GetConditionBySkillName(string skillName) {
    if (_condition.ContainsKey(skillName)) return _conditions[skillName];
    return new NoCondition();
  }
  
  /* ... */
}
```

En este ejemplo, las clases que utilizan `CatalogCondition` no tienen como saber que se está utilizando un `Dictionary`, no estamos recibiendo `Dictionary` en ningún método público, ni lo estamos retornando, y si el día de mañana queremos utilizar otra clase en vez de `Dictionary`, sólo tenemos que editar esta clase.

Ahora, tienes que tener cuidado, porque puede que todo lo que mencioné arriba se cumpla para alguna de tus clases, pero puede que tu clase tenga más de una responsabilidad. Para analizar ese caso, hay que hacerse las preguntas de rigor (¿Cuáles son las razones de cambio de esta clase? ¿Es esta clase cohesiva?) y por último, estar conciente al momento de modificar clases a la hora de agregar nuevas features.

**Comment by martina-abello** [comment]
ah. y si encapsulé arrays, está bien igual, o los tengo que desencapsular?

**Comment by cahinostroza** [comment]
Puedes dejarlo así :)

**Comment by martina-abello** [comment]
thank you ^^
