### ISSUE TITLE
[E4] Duda sobre habilidad Flare

### ISSUE THREAD

**Issue by martina-abello** [franciscogazitua/IIC2113-2024#206]
Hola, para el penalty de esta  habilidad, debería usarse Floor o Round para pasar a int el 20% de la resistencia del rival? Pasa que cuando uso cualquiera me falla el test 015, me sale con ambos
![image](https://github.com/user-attachments/assets/3c5ef651-5ebc-4448-b58f-f05de3d5892e)
así que no sé cuál es la parte que falla. gracias de antemano!

**Comment by cahinostroza** [comment]
Yo creo que estás utilizando el stat de la unidad incorrecta, porque si utilizas la de Robin `35*0.2=7` no hay chance que te de 6, pero en este caso tienes que tomar el stat de Verónica `32*0.2=6.4`, ahí ya sea que utilices `Floor` o `Round`, deberías tener el resultado esperado.
Y con respecto a tu pregunta original, yo utilizo `Floor` y no he tenido problemas.

**Comment by martina-abello** [comment]
ya, sí, sorry. es que no había cachado que la habilidad usaba como base *el valor base* de Res. El enunciado no lo deja claro, así que yo asumí que era como las otras habilidades con las que había que implementar los bonus/penalty antes.
