### ISSUE TITLE
[E2] Consola muestra resultados correctos, pero el test falla.

### ISSUE THREAD

**Issue by TFreyre23** [franciscogazitua/IIC2113-2024#41]
En el test 65 de la carpeta E2 al correr todos los tests me sale que falla por el error mostrado en la imagen. Pero al momento de correr el programa y ejecutar ese test en especifico corre perfeectamente y el test termina sin errores.
Porque podría estar pasando esto?
(ya revise el test en si y no ha sido modificado el .txt)
<img width="511" alt="Captura de pantalla 2024-04-21 a la(s) 2 20 25 a  m" src="https://github.com/franciscogazitua/IIC2113-2024/assets/69522067/e6294282-db8c-45d2-bfdf-77f960f122bb">
<img width="826" alt="Captura de pantalla 2024-04-21 a la(s) 2 21 03 a  m" src="https://github.com/franciscogazitua/IIC2113-2024/assets/69522067/ea2df545-c094-441e-b9c6-58b44294a8e7">

**Comment by RodrigoToroIcarte** [comment]
¿Bajaste la nueva versión del código base y de la carpeta data que subimos para la E2?

... una opción que se me ocurre es que no estés ejecutando el test 65 en la vista manual. Había un desfase en la enumeración de los test cases en la data que subimos para la E1. Por ejemplo, para ejecutar el test 65 creo que debías ingresar como input 66. En parte por eso subimos otra carpeta data para la E2.

Una forma fácil de verificar esto es que al momento de replicar un test sale un mensaje indicando qué test se está replicando:

![Screenshot from 2024-04-21 02-33-00](https://github.com/franciscogazitua/IIC2113-2024/assets/7000518/adabbced-fa42-40c2-886a-56ac771dbf34)

**Comment by RodrigoToroIcarte** [comment]
Mmm... miré el test en cuestión y sí es el test que estás replicando :/

Otra opción es que sean cosas static que te están jugando en contra. Si replicas el test de manera individual pasas ese test?

(Para replicar el test de manera individual hay que hacer click derecho en el test 65 y poner run unit test)

**Comment by RodrigoToroIcarte** [comment]
Lo otro que podrías intentar es correr el test en modo debug. Eso hará que te muestre la línea en la que se cae y el valor de las variables locales. Así puedes ver porqué se produce el error.

![Screenshot from 2024-04-21 02-57-05](https://github.com/franciscogazitua/IIC2113-2024/assets/7000518/177599a6-f9f8-46f0-802a-483989a45870)

**Comment by TFreyre23** [comment]
Hola profesor, al correr el test de manera individual si lo pasa correctamente. Entonces al correr todos los tests falla pero si lo corro individualmente esta correcto. Me debería preocupar por este problema o lo dejo tal cual esta?
Gracias.

**Comment by RodrigoToroIcarte** [comment]
Sí, te debe preocupar. El problema es que tienes atributos static en tu código. Los tests se corren en paralelo usando multithreads. Pero las cosas statics son las mismas para todos los threads. Por lo mismo, si en un test cambias su valor se cambia en todos los threads.

Convierte todos tus atributos static en atributos normales y vas a pasar los test cases.

Como fun fact... esto no es un problema del proyecto del curso. Las cosas static son difíciles de testear. Por eso la gente al final prefiere no usarlas mucho. Los métodos static no son problema. Son los atributos static los que rompen las cosas :/

**Comment by TFreyre23** [comment]
Ok gracias profesor, cambiare los atributos statics a normal nomas.
