### ISSUE TITLE
[E2] Error al correr unit tests

### ISSUE THREAD

**Issue by vrodriguez-py** [franciscogazitua/IIC2113-2024#44]
Hola, 
Tengo el siguiente error al tratar de correr los tests. Los tests de la E1 pasan correctamente pero todos los otros muestran el mismo error. Nose porque busca ese archivo en vez de el nombre completo.
Alguna ayuda?

![image](https://github.com/franciscogazitua/IIC2113-2024/assets/69616807/4f63de18-382a-46ad-8778-21a36f036004)

**Comment by RodrigoToroIcarte** [comment]
Yo creo que harcodeaste los nombres de los archivos a los equipos. En la E1 justo los archivos de equipos se llamaban `000.txt`, `001.txt`, etc. En la E2 los nombres de los archivos a los equipos también incluyen una descripción de la habilidad que evalúan, como por ejemplo `000__Bonus_Armored_Blow.txt`. 

Revisa tu código que genera el nombre del archivo a leer (el `000.txt`). Creo que ahí está el problema.

**Comment by vrodriguez-py** [comment]
toda la razon, gracias
