### ISSUE TITLE
Problema al correr los test manualmente

### ISSUE THREAD

**Issue by Javipipi** [franciscogazitua/IIC2113-2024#53]
Hola, al correr el test manual me sale error al imprimir las opciones de unidades a elegir, pero el output es el mismo. Al correr todos los test con la carpeta .Tests mi código se cae más adelante, pero este problema del test manual no me permite debuggear correctamente

![Captura de pantalla 2024-04-26 a la(s) 15 30 30](https://github.com/franciscogazitua/IIC2113-2024/assets/106037665/f75e2d20-c09f-49f4-a5f7-3579f0dc8115)

**Comment by RodrigoToroIcarte** [comment]
¿Será que tienes un espacio extra en el `0: Lucina`? Algo como `0: Lucina `?

¿Te pasa en todos los test cases o solo en este?

**Comment by Javipipi** [comment]
Me pasa solo en los test de la entrega 2 para arriba, en la entrega 1 no, pero ya lo resolví así que gracias igual!
