### ISSUE TITLE
[E3] Duda sobre cohesión de clases.

### ISSUE THREAD

**Issue by cristobalSaravia** [franciscogazitua/IIC2113-2024#63]
Hola, tengo una duda con respecto al caso de métodos de una clase que no ocupen ningún atributo de la clase para realizar su función. En estos casos se debería también separar en una clase aparte?

**Comment by RodrigoToroIcarte** [comment]
La clave es el tema de las responsabilidades de la clase. Mirar la cohesión de una clase sirve como heurística (o hint) para indicar que una clase podría tener más de una responsabilidad. Entonces, para responder tu pregunta, necesitaría un ejemplo. A priori, me parece curioso que tengas un método que no use ningún atributo de su clase. Me hace cuestionarme porqué está ese método ahí ;)

**Comment by cristobalSaravia** [comment]
Me di cuenta que la clase con métodos que no ocupaban atributos no necesitaba tener atributos en primer lugar, entonces no tenía mucho sentido la pregunta, muchas gracias!!
